#! /bin/bash

# removing old files
make clean
rm sisl/include/*.h 2> /dev/null
rm sisl/src/*.c 2> /dev/null

# copying header files
HEADERFILES="sisl.h sislP.h"  # those headerfiles relevant for the GPL version

for n in $HEADERFILES
do
  TARGETNAME=sisl/include/$n

  #writing preliminary include guard
  head --lines=2 ../include/$n > $TARGETNAME
  #writing obligatory header
  cat license_header >> $TARGETNAME
  #writing rest of file
  if $n eq sislP.h
  then
    tail ../include/$n -n+19 >> $TARGETNAME
  else 
    tail ../include/$n -n+32 >> $TARGETNAME
  fi
done
cp license_header sisl/include/copyright.h

#cp ../include/*.h sisl/include/

# generating source files
SOURCEFILES=`ls ../src/*.c`

# make sure the 'removecomments' program is compiled
g++ -O3 removecomments.C -o removecomments

for n in $SOURCEFILES
do
   FILENAME=`basename $n`
   TARGETNAME=sisl/src/$FILENAME

   # writing obligatory header
   cat license_header > $TARGETNAME

   # determining whether comments should be removed
   # or not
   if test `grep $FILENAME documented_routines`
   then
      # this routine should be docummented.
      # writing file, minus header to target
      tail $n -n+9 >> $TARGETNAME
      echo $FILENAME documented.
   else
      # we need to remove comments from this file
      # before writing it to target.
      ./removecomments < $n > xcmklp_temp
      cat xcmklp_temp >> $TARGETNAME
      rm xcmklp_temp
      echo $FILENAME undocumented.      
   fi
      
done

#making zipped file of everything
mkdir sisl_4.4_gpl
cp -r doc sisl_4.4_gpl
cp -r examples sisl_4.4_gpl
cp -r sisl sisl_4.4_gpl
cp -r streming sisl_4.4_gpl
cp -r viewer sisl_4.4_gpl

cp COPYING sisl_4.4_gpl
cp Makefile sisl_4.4_gpl
cp makefile_template sisl_4.4_gpl
cp README sisl_4.4_gpl

#removing CVS catalogues
rm -r sisl_4.4_gpl/doc/CVS
rm -r sisl_4.4_gpl/doc/manual/CVS
rm -r sisl_4.4_gpl/doc/manual/tex/CVS
rm -r sisl_4.4_gpl/doc/manual/tex/func/CVS
rm -r sisl_4.4_gpl/doc/manual/text/type/CVS
rm -r sisl_4.4_gpl/doc/users_guide/CVS
rm -r sisl_4.4_gpl/doc/users_guide/tex/CVS
rm -r sisl_4.4_gpl/examples/CVS
rm -r sisl_4.4_gpl/examples/lib/CVS
rm -r sisl_4.4_gpl/sisl/CVS
rm -r sisl_4.4_gpl/sisl/include/CVS
rm -r sisl_4.4_gpl/sisl/lib/CVS
rm -r sisl_4.4_gpl/sisl/src/CVS
rm -r sisl_4.4_gpl/streaming/CVS
rm -r sisl_4.4_gpl/streaming/include/CVS
rm -r sisl_4.4_gpl/streaming/include/lib/CVS
rm -r sisl_4.4_gpl/streaming/src/CVS
rm -r sisl_4.4_gpl/viewer/CVS
rm -r sisl_4.4_gpl/viewer/include/CVS
rm -r sisl_4.4_gpl/viewer/lib/CVS
rm -r sisl_4.4_gpl/viewer/src/CVS

#packing everything
tar -zcvf sisl_4.4_gpl.tgz sisl_4.4_gpl

