all:;
	cd sisl; make lib
	cd streaming; make lib
	cd viewer; make sisl_view_demo
	cd examples; make example01
	cd examples; make example02
	cd examples; make example03
	cd examples; make example04
	cd examples; make example05
	cd examples; make example06
	cd examples; make example07
	cd examples; make example08
	cd examples; make example09
	cd examples; make example10
	cd examples; make example11
	cd examples; make example12
	cd examples; make example13
	cd examples; make example14
	cd examples; make example15

.PHONY: clean

clean:
	cd sisl; make clean
	cd streaming; make clean
	cd viewer; make clean
	cd examples; make clean
